# Generated by Django 4.1.5 on 2023-01-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profileimg",
            field=models.ImageField(
                default="blank-profile-picture.png", upload_to="profile_images"
            ),
        ),
    ]
