# Generated by Django 4.1.5 on 2023-01-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_profile_age"),
    ]

    operations = [
        migrations.CreateModel(
            name="Acourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("lecturer", models.CharField(max_length=100)),
                ("no_of_lectures", models.IntegerField(default=0)),
                ("no_of_lectures_attended", models.IntegerField(default=0)),
                ("no_of_lectures_missed", models.IntegerField(default=0)),
                ("no_of_lectures_left", models.IntegerField(default=0)),
                ("minmum_attendance", models.IntegerField(default=0)),
            ],
        ),
    ]
