# Generated by Django 4.1.5 on 2023-01-14 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_acourse"),
    ]

    operations = [
        migrations.DeleteModel(name="Acourse",),
    ]
