# Generated by Django 4.1.5 on 2023-01-14 15:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_name",
            field=models.CharField(default="course", max_length=100),
        ),
        migrations.AddField(
            model_name="course",
            name="lec_missed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="course",
            name="minimum_attendance",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="course",
            name="total_lecs",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="course",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
