# Generated by Django 4.1.5 on 2023-01-14 16:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_course_course_name_course_lec_missed_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Missed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=datetime.datetime.now)),
                ("no_of_missed", models.IntegerField(default=0)),
                (
                    "course_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.course"
                    ),
                ),
            ],
        ),
    ]
