# Generated by Django 4.1.5 on 2023-01-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_missed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missed",
            name="course_id",
            field=models.CharField(max_length=100),
        ),
    ]
