# Generated by Django 4.1.5 on 2023-01-14 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_missed_course_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="missed", name="date",),
        migrations.RemoveField(model_name="missed", name="no_of_missed",),
    ]
