# Generated by Django 4.1.5 on 2023-01-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_missed_date_remove_missed_no_of_missed"),
    ]

    operations = [
        migrations.DeleteModel(name="Missed",),
        migrations.AddField(
            model_name="course",
            name="lec_can_be_missed",
            field=models.IntegerField(default=0),
        ),
    ]
