# Generated by Django 4.1.5 on 2023-01-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_expense_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="expense_limit",
            field=models.IntegerField(default=0),
        ),
    ]
