# Generated by Django 4.1.5 on 2023-01-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_expense_expense_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="month",
            field=models.CharField(default="month", max_length=100),
        ),
    ]
