# Generated by Django 4.1.5 on 2023-01-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_budget_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="remaining_amount",
            field=models.IntegerField(default=0),
        ),
    ]
