# Generated by Django 4.1.5 on 2023-01-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_remove_notes_note_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="note_id",
            field=models.CharField(default="note", max_length=100),
        ),
    ]
