# Generated by Django 4.1.5 on 2023-01-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_file_note_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="file",
            field=models.FileField(default="blank.pdf", upload_to="notes_files"),
        ),
        migrations.DeleteModel(name="File",),
    ]
