# Generated by Django 4.1.5 on 2023-01-19 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0024_notes_file_delete_file"),
    ]

    operations = [
        migrations.RemoveField(model_name="notes", name="file",),
        migrations.CreateModel(
            name="DOCS",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="doc", max_length=100)),
                ("file", models.FileField(default="blank.pdf", upload_to="docs")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
