# Generated by Django 4.1.5 on 2023-01-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_remove_notes_file_docs"),
    ]

    operations = [
        migrations.AddField(
            model_name="docs",
            name="note_id",
            field=models.CharField(default="note", max_length=100),
        ),
    ]
